---
- name: Configure WebServers
  hosts: webservers
  become: yes
  tasks:
  - name: Ensure Apache is installed
    package: 
      name: httpd
      state: present


  - name: Copy a web page
    copy:
      content: |
        <html>
        <head><title>Hello World</title></head>
        <body>Hello World</body>
        </html>
      dest: /var/www/html/index.html
    notify: restart apache
 
  - name: Ensure Service is running
    service:
      name: httpd
      state: started
      enabled: true

  handlers:
  - name: restart apache
    service:
      name: httpd
      state: restarted


      
- name: Configure HAProxy
  hosts: loadbalancers
  become: yes
  tasks:
    - name: Install HAProxy
      ansible.builtin.package:
        name: haproxy
        state: present

    - name: Deploy HAProxy configuration
      ansible.builtin.template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: '0644'
      notify: Restart HAProxy

  handlers:
    - name: Restart HAProxy
      ansible.builtin.service:
        name: haproxy
        state: restarted
        enable: true
